// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package automationactionsaction

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-pagerduty.automationActionsAction.AutomationActionsAction",
		reflect.TypeOf((*AutomationActionsAction)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "actionClassification", GoGetter: "ActionClassification"},
			_jsii_.MemberProperty{JsiiProperty: "actionClassificationInput", GoGetter: "ActionClassificationInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionDataReference", GoGetter: "ActionDataReference"},
			_jsii_.MemberProperty{JsiiProperty: "actionDataReferenceInput", GoGetter: "ActionDataReferenceInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionType", GoGetter: "ActionType"},
			_jsii_.MemberProperty{JsiiProperty: "actionTypeInput", GoGetter: "ActionTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowInvocationFromEventOrchestration", GoGetter: "AllowInvocationFromEventOrchestration"},
			_jsii_.MemberProperty{JsiiProperty: "allowInvocationFromEventOrchestrationInput", GoGetter: "AllowInvocationFromEventOrchestrationInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowInvocationManually", GoGetter: "AllowInvocationManually"},
			_jsii_.MemberProperty{JsiiProperty: "allowInvocationManuallyInput", GoGetter: "AllowInvocationManuallyInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "creationTime", GoGetter: "CreationTime"},
			_jsii_.MemberProperty{JsiiProperty: "creationTimeInput", GoGetter: "CreationTimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "mapToAllServices", GoGetter: "MapToAllServices"},
			_jsii_.MemberProperty{JsiiProperty: "mapToAllServicesInput", GoGetter: "MapToAllServicesInput"},
			_jsii_.MemberProperty{JsiiProperty: "modifyTime", GoGetter: "ModifyTime"},
			_jsii_.MemberProperty{JsiiProperty: "modifyTimeInput", GoGetter: "ModifyTimeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "onlyInvocableOnUnresolvedIncidents", GoGetter: "OnlyInvocableOnUnresolvedIncidents"},
			_jsii_.MemberProperty{JsiiProperty: "onlyInvocableOnUnresolvedIncidentsInput", GoGetter: "OnlyInvocableOnUnresolvedIncidentsInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putActionDataReference", GoMethod: "PutActionDataReference"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionClassification", GoMethod: "ResetActionClassification"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowInvocationFromEventOrchestration", GoMethod: "ResetAllowInvocationFromEventOrchestration"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowInvocationManually", GoMethod: "ResetAllowInvocationManually"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreationTime", GoMethod: "ResetCreationTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMapToAllServices", GoMethod: "ResetMapToAllServices"},
			_jsii_.MemberMethod{JsiiMethod: "resetModifyTime", GoMethod: "ResetModifyTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetOnlyInvocableOnUnresolvedIncidents", GoMethod: "ResetOnlyInvocableOnUnresolvedIncidents"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunnerId", GoMethod: "ResetRunnerId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunnerType", GoMethod: "ResetRunnerType"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberProperty{JsiiProperty: "runnerId", GoGetter: "RunnerId"},
			_jsii_.MemberProperty{JsiiProperty: "runnerIdInput", GoGetter: "RunnerIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "runnerType", GoGetter: "RunnerType"},
			_jsii_.MemberProperty{JsiiProperty: "runnerTypeInput", GoGetter: "RunnerTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_AutomationActionsAction{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-pagerduty.automationActionsAction.AutomationActionsActionActionDataReference",
		reflect.TypeOf((*AutomationActionsActionActionDataReference)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-pagerduty.automationActionsAction.AutomationActionsActionActionDataReferenceOutputReference",
		reflect.TypeOf((*AutomationActionsActionActionDataReferenceOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "invocationCommand", GoGetter: "InvocationCommand"},
			_jsii_.MemberProperty{JsiiProperty: "invocationCommandInput", GoGetter: "InvocationCommandInput"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationJobArguments", GoGetter: "ProcessAutomationJobArguments"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationJobArgumentsInput", GoGetter: "ProcessAutomationJobArgumentsInput"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationJobId", GoGetter: "ProcessAutomationJobId"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationJobIdInput", GoGetter: "ProcessAutomationJobIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationNodeFilter", GoGetter: "ProcessAutomationNodeFilter"},
			_jsii_.MemberProperty{JsiiProperty: "processAutomationNodeFilterInput", GoGetter: "ProcessAutomationNodeFilterInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetInvocationCommand", GoMethod: "ResetInvocationCommand"},
			_jsii_.MemberMethod{JsiiMethod: "resetProcessAutomationJobArguments", GoMethod: "ResetProcessAutomationJobArguments"},
			_jsii_.MemberMethod{JsiiMethod: "resetProcessAutomationJobId", GoMethod: "ResetProcessAutomationJobId"},
			_jsii_.MemberMethod{JsiiMethod: "resetProcessAutomationNodeFilter", GoMethod: "ResetProcessAutomationNodeFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetScript", GoMethod: "ResetScript"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "script", GoGetter: "Script"},
			_jsii_.MemberProperty{JsiiProperty: "scriptInput", GoGetter: "ScriptInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_AutomationActionsActionActionDataReferenceOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-pagerduty.automationActionsAction.AutomationActionsActionConfig",
		reflect.TypeOf((*AutomationActionsActionConfig)(nil)).Elem(),
	)
}
